Submitting project for review
matheus-fls/TNW-Clone pull request #3
Opened 2019-07-26 23:56 UTC by matheus-fls

2019-07-27 02:26 UTC, bolah2009 commented
Currently under review

2019-07-27 03:04 UTC, bolah2009 requested changes
### Hi Team :wave: 

Nice job so far, the [clone](https://raw.githack.com/matheus-fls/TNW-Clone/development/index.html) looks nice and responsive. :clap: :+1: 

However. there are some sections in the [original site](https://thenextweb.com/) that are missing, kindly add those, make them responsive and submit for another review.

##### Please note that this review may not be comprehensive enough because the project is not yet complete.

Good luck with your next submission.

Cheers
[Bola](https://bolabuari.com/)

2019-07-27 03:04 UTC, bolah2009 commented on index.html
> +                        <li><a href="#">E</a></li>
`REQUIRED`

Consider using social media icons.

2019-07-27 03:04 UTC, bolah2009 commented on index.html
> +                    <p>Kudos to the awesome devs at <a href="https://www.stackpath.com/">Stackpath</a> who made the original page.</p>
`SUGGESTION`

Use the content on the footer instead. See below:

![tnw footer](https://user-images.githubusercontent.com/36057474/61989108-62887f00-b022-11e9-8f34-0b7b09f16a2b.png)

2019-07-30 00:55 UTC, Torres-ssf commented
### Pull Request Under Review By Sérgio (TSE)

2019-07-30 01:10 UTC, Torres-ssf commented
### Way to go team 👏
Nice job building the responsive page. I'm giving this project a 👍. Go on and merge to master. Good luck with the next one.

2019-07-30 15:33 UTC, merged